###
# Copyright (c) Mainflux
#
# Mainflux server is licensed under an Apache license, version 2.0 license.
# All rights not explicitly granted in the Apache license, version 2.0 are reserved.
# See the included LICENSE file for more details.
###

###
# MongoDB
###
mongo:
  image: mongo:latest
  container_name: mainflux-mongodb
  command: --smallfiles --nojournal

###
# Flux M2M
###
fluxm2m:
  image: mainflux/fluxm2m:latest
  container_name: fluxm2m
  links:
    - mongo
  ports:
    - "9099:9099"

